spring:
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url中必须指定时区
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  #jpa配置
  jpa:
    hibernate:
      ddl-auto: update  #连接数据库时比对当前项目实体对象与数据库是否一致，不一致则更新数据库，生产环境时改为none
    show-sql: true  #在控制台和日志输出sql语句
  #模版配置
  thymeleaf:
    cache: false
  #热部署
  devtools:
    restart:
      enabled: true

# 配置日志
logging:
  level:
    root: info  #springboot框架本身的级别，默认info
    com.mfj: debug  #自定义包
  file:
    path: /log
    name: blog-dev.log
